platform:
  - x64

cache:
  - '%LOCALAPPDATA%\electron\Cache'
  - node_modules -> package.json

install:
  - systeminfo | findstr /C:"OS"
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ps: Install-Product node 6 x64
  - yarn install

build_script:
  - yarn eslint
  - yarn test-server
  - yarn run icon-gen
  - node build\grunt.js
  - type package.json | findstr /v certificateSubjectName > temp.json
  - move temp.json package.json
  - yarn prepare-build
  - node_modules\.bin\build --em.environment=%SIGNAL_ENV% --publish=never

test_script:
  - node build\grunt.js test-release:win
  - node build\grunt.js test

environment:
  SIGNAL_ENV: production
